const QUOTES = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", focus: "Passion" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", focus: "Self-Belief" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", focus: "Inner Strength" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", focus: "Joy" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln", focus: "Purpose" },
  { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman", focus: "Optimism" },
  { text: "Gratitude turns what we have into enough.", author: "Anonymous", focus: "Gratitude" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", focus: "Growth" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", focus: "Authenticity" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", focus: "Resilience" },
  { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain", focus: "Kindness" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", focus: "Mindfulness" },
  { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats", focus: "Action" },
  { text: "Every day may not be good, but there is something good in every day.", author: "Alice Morse Earle", focus: "Hope" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha", focus: "Calm" },
  { text: "The struggle you're in today is developing the strength you need for tomorrow.", author: "Robert Tew", focus: "Patience" },
  { text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha", focus: "Self-Love" },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien", focus: "Consistency" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", focus: "Growth" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", focus: "Simplicity" },
  { text: "Every moment is a fresh beginning.", author: "T.S. Eliot", focus: "New Beginnings" },
  { text: "Courage doesn't always roar. Sometimes it's the quiet voice at the end of the day saying, 'I will try again tomorrow.'", author: "Mary Anne Radmacher", focus: "Courage" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", focus: "Confidence" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", focus: "Impact" },
  { text: "Stay close to anything that makes you glad you are alive.", author: "Hafiz", focus: "Joy" },
  { text: "Slow down and everything you are chasing will come around and catch you.", author: "John De Paola", focus: "Balance" },
  { text: "You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr.", focus: "Courage" },
  { text: "An open mind is the beginning of self-discovery and growth.", author: "Anonymous", focus: "Open-Mindedness" },
  { text: "The soul that sees beauty may sometimes walk alone.", author: "Johann Wolfgang von Goethe", focus: "Presence" },
  { text: "Wherever you go, go with all your heart.", author: "Confucius", focus: "Presence" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", focus: "Perseverance" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", focus: "Courage" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", focus: "Vision" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", focus: "Presence" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", focus: "Action" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", focus: "Letting Go" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", focus: "Persistence" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", focus: "Mindset" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", focus: "Self-Direction" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", focus: "Courage" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", focus: "Resourcefulness" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'.", author: "Audrey Hepburn", focus: "Possibility" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", focus: "Risk-Taking" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain", focus: "Purpose" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi", focus: "Resilience" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale", focus: "Perspective" },
  { text: "The harder I work, the luckier I get.", author: "Samuel Goldwyn", focus: "Effort" },
  { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou", focus: "Creativity" },
  { text: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", author: "Mother Teresa", focus: "Impact" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", focus: "Action" },
  { text: "Peace begins with a smile.", author: "Mother Teresa", focus: "Kindness" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien", focus: "Exploration" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle", focus: "Self-Responsibility" },
  { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll", focus: "Response" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", focus: "Resourcefulness" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", focus: "Resilience" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", focus: "Authenticity" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu", focus: "Beginnings" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost", focus: "Perspective" },
  { text: "Everything has beauty, but not everyone can see it.", author: "Confucius", focus: "Awareness" },
  { text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou", focus: "Kindness" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", focus: "Discipline" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar", focus: "Perseverance" },
  { text: "The best way out is always through.", author: "Robert Frost", focus: "Perseverance" },
  { text: "Optimism is the faith that leads to achievement.", author: "Helen Keller", focus: "Optimism" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", focus: "Individuality" },
  { text: "There is only one thing that makes a dream impossible to achieve: the fear of failure.", author: "Paulo Coelho", focus: "Fear" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin", focus: "Courage" },
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne", focus: "Self-Belief" },
  { text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson", focus: "Connection" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi", focus: "Integrity" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", focus: "Aliveness" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", focus: "Growth" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot", focus: "Persistence" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", focus: "Growth" },
  { text: "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.", author: "Anonymous", focus: "Calm" },
  { text: "Enjoy the little things, for one day you may look back and realize they were the big things.", author: "Robert Brault", focus: "Gratitude" },
  { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy", focus: "Inner Strength" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", focus: "Beginnings" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", focus: "Persistence" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", focus: "Hope" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", focus: "Joy" },
  { text: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis", focus: "New Beginnings" },
  { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson", focus: "Self-Belief" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb", focus: "Action" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb", focus: "Resilience" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy", focus: "Patience" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem", focus: "Confidence" },
  { text: "Act the way you'd like to be and soon you'll be the way you act.", author: "Leonard Cohen", focus: "Growth" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin", focus: "Persistence" },
];
